REVOKE ALL FROM ubnt;
DROP USER IF EXISTS ubnt;
DROP DATABASE IF EXISTS unms;

CREATE USER ubnt WITH PASSWORD 'ubnt';
GRANT ALL PRIVILEGES ON DATABASE unms to ubnt;
GRANT ALL ON ALL TABLES IN SCHEMA public TO ubnt;
